export const ADDINGREDIENT='ADDINGREDIENT';
export const REMOVEINGREDIENT='REMOVEINGREDIENT';
export const INITINGREDIENT='INITINGREDIENT';
export const FETCHINGREDIENTFAILED = 'FETCHINGREDIENTFAILED';
export const INIT_INGREDIENT_SAGA = 'INIT_INGREDIENT_SAGA';

export const PURCHASE_BURGER_SUCCESS='PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAILED='PURCHASE_BURGER_FAILED';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SAGA = 'PURCHASE_BURGER_SAGA';

export const PURCHASE_INIT='PURCHASE_INIT';

export const FETCH_ORDER_START='FETCH_ORDER_START';
export const FETCH_ORDER_SUCCESS='FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILED = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_SAGA = 'FETCH_ORDER_SAGA';

export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAILED='AUTH_FAILED';
export const AUTH_LOGOUT='AUTH_LOGOUT';
export const AUTH_INIT_LOGOUT='AUTH_INIT_LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_CHECK_INITIAL_STATE = 'AUTH_CHECK_INITIAL_STATE';

export const SET_AUTH_REDIRECT_PATH='SET_AUTH_REDIRECT_PATH';